name: Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
    # repository_dispatch:
    #     types: [trigger_build]

    # workflow_dispatch:
    #     inputs:
    #         buildType:
    #             description: 'Type de build'
    #             required: true
    #             type: choice
    #             options: 
    #               - force
    #               - pull_request
    #               - other
    #             default: 'default'

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          buildType: ${{ steps.log_build_type.outputs.buildType }}
        steps:
            - name: Log input
              id: log_build_type
              run: |
                # Set the buildType based on the event
                  build_type="${{ github.event_name }}"
                echo "buildType=$build_type" >> "$GITHUB_OUTPUT"
                echo "logging input: $build_type"


    checkup:
        runs-on: ubuntu-latest
        permissions:
          issues: write
        needs: build
        strategy:
            matrix:
                directory: [
                    service1,
                    service2,
                    service3,
                    service4,
                    service5,
                ]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.PERSONAL_TOKEN }}
                fetch-depth: 2

            - name: Install GitHub CLI
              run: |
                sudo apt-get install -y gh

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v45

            - name: Check for changes
              id: check_changes
              run: |
                # Define the directory to monitor
                directory="src/${{ matrix.directory }}"
                
                # Get the list of changed files
                changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
                
                echo "Gonna show files"
                # Check if any of the changed files are in the target directory
                build_needed="false"
                for file in $changed_files; do
                  echo $file
                  if [[ "$file" == $directory* ]]; then
                    build_needed="true"
                    break
                  fi
                done

                if [[ "$build_needed" == "true" ]]; then
                  echo "On build"
                  echo "::set-output name=build_needed::true"
                else
                  echo "Pas de build"
                  echo "::set-output name=build_needed::false"
                fi
            
            - name: Skip job if no changes
              if: steps.check_changes.outputs.build_needed == 'false' && needs.build.outputs.buildType != 'force'
              run: |
                echo "Pas de build - marking as skipped"
              continue-on-error: true
            
            - name: Build process
              if: steps.check_changes.outputs.build_needed == 'true' || needs.build.outputs.buildType == 'force'
              run: |
                echo "On build"
                # Add your build steps here

            - name: try something
              run: echo ${{ needs.build.outputs.buildType }}
   
            - name: Add labels to PR
              if: needs.build.outputs.buildType == 'pull_request' && (steps.check_changes.outputs.build_needed == 'true' || needs.build.outputs.buildType == 'force')
              uses: actions-ecosystem/action-add-labels@v1
              with:
                github_token: ${{ secrets.PERSONAL_TOKEN }}
                labels: |
                  ${{ matrix.directory }}

            - name: No Label this is not a pull_request
              if: needs.build.outputs.buildType != 'pull_request' && (steps.check_changes.outputs.build_needed == 'true' || needs.build.outputs.buildType == 'force' )
              run: echo "This is not a pull request, skipping label addition."