name: Build

on:
    repository_dispatch:
        types: [trigger_build]
    workflow_dispatch:
        inputs:
            buildType:
                description: 'Type de build'
                required: true
                type: choice
                options: 
                  - force
                  - pull_request
                  - other

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Log input
              run: |
                  echo "Projet A avec la valeur ${{ github.event.inputs.buildType }}"

    checkup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                directory: [
                    service1,
                    service2,
                    service3,
                    service4,
                    service5,
                ]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Install GitHub CLI
              run: |
                sudo apt-get install -y gh

            - name: Check for changes
              id: check_changes
              run: |
                cd src/${{ matrix.directory }}
                if git diff --quiet HEAD^ HEAD .; then
                    echo "Pas de build"
                    echo "::set-output name=build_needed::false"
                else
                    echo "On build"
                    echo "::set-output name=build_needed::true"
                fi
            
            - name: Skip job if no changes
              if: steps.check_changes.outputs.build_needed == 'false' && github.event.inputs.buildType != 'force'
              run: |
                echo "Pas de build - marking as skipped"
              continue-on-error: true
            
            - name: Build process
              if: steps.check_changes.outputs.build_needed == 'true' || github.event.inputs.buildType == 'force'
              run: |
                echo "On build"
                # Add your build steps here

            - name: try something
              run: echo ${{ github.event.inputs.buildType }}
   
            - name: Add labels to PR
              if: github.event.inputs.buildType == 'pull_request' && (steps.check_changes.outputs.build_needed == 'true' || github.event.inputs.buildType == 'force' )
              uses: actions-ecosystem/action-add-labels@v1
              with:
                labels: |
                  ${{ matrix.directory }}

            - name: No Label this is not a pull_request
              if: github.event.inputs.buildType != 'pull_request' && (steps.check_changes.outputs.build_needed == 'true' || github.event.inputs.buildType == 'force' )
              run: echo "This is not a pull request, skipping label addition."