name: Build

on:
    repository_dispatch:
        types: [trigger_build]

    workflow_dispatch:
        inputs:
            buildType:
                description: 'Type de build'
                required: true
                type: choice
                options: 
                  - force
                  - pull_request
                  - other
                default: 'default'

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          buildType: ${{ steps.log_build_type.outputs.buildType }}
        steps:
            - name: Log input
              id: log_build_type
              run: |
                # Set the buildType based on the event
                if [ -n "${{ github.event.client_payload.buildType }}" ]; then
                  build_type="${{ github.event.client_payload.buildType }}"
                else
                  build_type="${{ github.event.inputs.buildType }}"
                fi
                echo "buildType=$build_type" >> "$GITHUB_OUTPUT"
                echo "logging input: $build_type"


    checkup:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            matrix:
                directory: [
                    service1,
                    service2,
                    service3,
                    service4,
                    service5,
                ]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Install GitHub CLI
              run: |
                sudo apt-get install -y gh

            - name: Fetch main branch
              run: |
                git fetch origin main:main

            - name: Check for changes
              id: check_changes
              run: |
                cd src/${{ matrix.directory }}
                if git diff --quiet origin/main...HEAD .; then
                    echo "Pas de build"
                    echo "::set-output name=build_needed::false"
                else
                    echo "On build"
                    echo "::set-output name=build_needed::true"
                fi
            
            - name: Skip job if no changes
              if: steps.check_changes.outputs.build_needed == 'false' && needs.build.outputs.buildType != 'force'
              run: |
                echo "Pas de build - marking as skipped"
              continue-on-error: true
            
            - name: Build process
              if: steps.check_changes.outputs.build_needed == 'true' || needs.build.outputs.buildType == 'force'
              run: |
                echo "On build"
                # Add your build steps here

            - name: try something
              run: echo ${{ needs.build.outputs.buildType }}
   
            - name: Add labels to PR
              if: needs.build.outputs.buildType == 'pull_request' && (steps.check_changes.outputs.build_needed == 'true' || needs.build.outputs.buildType == 'force' )
              uses: actions-ecosystem/action-add-labels@v1
              with:
                labels: |
                  ${{ matrix.directory }}

            - name: No Label this is not a pull_request
              if: needs.build.outputs.buildType != 'pull_request' && (steps.check_changes.outputs.build_needed == 'true' || needs.build.outputs.buildType == 'force' )
              run: echo "This is not a pull request, skipping label addition."