name: Build Fake A

on:
    workflow_dispatch:
        inputs:
            printval:
                description: 'valeur à afficher'
                required: false
                type: string

jobs:
    build:
        runs-on: ubuntu-latest  
        steps:
            - name: super build
              run: echo "projet A"
              env:
                PRINTVAL: ${{inputs.printval}}
