name: Build Fake A

on:
    repository_dispatch:
        types: [trigger_build_fake_a]
    workflow_dispatch:
        inputs:
            printval:
                description: 'valeur à afficher'
                required: false
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Super build
              run: |
                if [ -n "${{ github.event.client_payload.printval }}" ]; then
                    echo "Projet A avec la valeur : ${{ github.event.client_payload.printval }}"
                else
                    echo "Projet A avec la valeur : ${{ inputs.printval }}"
                fi

    checkup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                directory: [
                    service1,
                    service2,
                    service3,
                    service4,
                    service5,
                ]
        steps:
            - name: Checkout ${{ matrix.directory }}
              uses: actions/checkout@v3
              with:
                fetch-depth: 2 # To ensure we have at least the last two commits

            - name: Check if there were changes in the directory
              run: |
                cd src/${{ matrix.directory }}
                if git diff --quiet HEAD^ HEAD .; then
                    echo "Pas de build"
                else
                    echo "On build"
                fi
