name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  classic-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Log all github context variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "---------------------------------"
          echo "before: ${{ github.event.before }}"
          echo "after: ${{ github.event.after }}"
          echo "sha: ${{ github.sha }}"
          echo "ref: ${{ github.ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "ref_protected: ${{ github.ref_protected }}"
          echo "event: ${{ github.event }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event_path: ${{ github.event_path }}"
          echo "event after: ${{ github.event.after }}"
          echo "event before: ${{ github.event.before }}"
          echo "event pull_request: ${{ github.event.pull_request }}"
          echo "event repository: ${{ github.event.repository }}"
          echo "event sender: ${{ github.event.sender }}"
