name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  classic-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Log all github context variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "---------------------------------"
          echo "before: ${{ github.event.before }}"
          echo "after: ${{ github.event.after }}"
          echo "sha: ${{ github.sha }}"

  call-eslint:
    uses: ./.github/workflows/workcall.yml
