name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  classic-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log all github context variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "---------------------------------"
          echo "before: ${{ github.event.before }}"
          echo "after: ${{ github.event.after }}"
          echo "sha: ${{ github.sha }}"
          echo "ref: ${{ github.ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "ref_protected: ${{ github.ref_protected }}"
          echo "event: ${{ github.event }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event_path: ${{ github.event_path }}"
          echo "event after: ${{ github.event.after }}"
          echo "event before: ${{ github.event.before }}"
          echo "event pull_request: ${{ github.event.pull_request }}"
          echo "event repository: ${{ github.event.repository }}"
          echo "event sender: ${{ github.event.sender }}"
          echo "branch_name: ${{ github.head_ref || github.ref_name }}"
          echo "---------------------------------"
          echo "BRANCH INFORMATION:"
          echo "Current branch: ${{ github.head_ref || github.ref_name }}"
          echo "Base branch: ${{ github.base_ref || 'N/A' }}"
          echo "Is PR: ${{ github.event_name == 'pull_request' }}"
          echo "Is protected branch: ${{ github.ref_protected }}"
          echo "Branch type: ${{ github.ref_type }}"

      - name: Test GitHub Deployments Limit
        if: github.event_name == 'pull_request'
        run: ./scripts/test-deployments.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }} 
          GITHUB_REF: ${{ github.head_ref || github.ref_name }}
