name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit and PR info
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Commit SHA of PR: ${{ github.event.pull_request.head.sha }}"
          echo "Commit SHA of base (main): ${{ github.event.pull_request.base.sha }}"
          echo "Branch name of PR: ${{ github.event.pull_request.head.ref }}"
      
      - name: Get commit details from PR
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }} \
            | jq '.commit'

  trigger-build-A:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI/CD Pipeline
        uses: actions/github-script@v6
        with:
          script: |
            const { octokit } = require('@actions/github');
            await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'launchFakeA.yml',
              ref: 'main',
              token: ${{secrets.PERSONAL_TOKEN}}
            });