name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  classic-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Log all github context variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "---------------------------------"
          echo "before: ${{ github.event.before }}"
          echo "after: ${{ github.event.after }}"
          echo "sha: ${{ github.sha }}"
          echo "ref: ${{ github.ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "ref_protected: ${{ github.ref_protected }}"
          echo "event: ${{ github.event }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event_path: ${{ github.event_path }}"
          echo "event after: ${{ github.event.after }}"
          echo "event before: ${{ github.event.before }}"
          echo "event pull_request: ${{ github.event.pull_request }}"
          echo "event repository: ${{ github.event.repository }}"
          echo "event sender: ${{ github.event.sender }}"
          echo "branch_name: ${{ github.head_ref || github.ref_name }}"
          echo "---------------------------------"
          echo "BRANCH INFORMATION:"
          echo "Current branch: ${{ github.head_ref || github.ref_name }}"
          echo "Base branch: ${{ github.base_ref || 'N/A' }}"
          echo "Is PR: ${{ github.event_name == 'pull_request' }}"
          echo "Is protected branch: ${{ github.ref_protected }}"
          echo "Branch type: ${{ github.ref_type }}"
          echo "---------------------------------"
          echo "EXTRACTED BRANCH INFORMATION:"
          echo "Current branch (from GITHUB_REF): $(echo $GITHUB_REF | sed 's/refs\/heads\///')"
          echo "Base branch (for push): ${{ github.event.repository.default_branch }}"

      - name: Check for open PRs
        if: github.event_name == 'push'
        run: |
          CURRENT_BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Checking for open PRs for branch: $CURRENT_BRANCH"

          # Get open PRs for the current branch
          PR_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:$CURRENT_BRANCH&state=open")

          # Check if there are any open PRs
          if [ $(echo "$PR_RESPONSE" | jq 'length') -gt 0 ]; then
            # Get the base branch of the first open PR
            BASE_BRANCH=$(echo "$PR_RESPONSE" | jq -r '.[0].base.ref')
            PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.[0].number')
            echo "Found open PR #$PR_NUMBER targeting $BASE_BRANCH"
            echo "PR_URL: https://github.com/${{ github.repository }}/pull/$PR_NUMBER"
          else
            echo "No open PRs found for branch $CURRENT_BRANCH"
          fi
