name: Dynamic Matrix SURE

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  get_services:
    runs-on: ubuntu-20.04
    outputs:
      modifiedServices: ${{ steps.node_script.outputs.modifiedServices }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Identify modified services
        id: node_script
        run: |
          node .github/workflow/scripts/get-changed-files.js
        env:
          CHANGED_FILES: ${{ toJson(steps.changed-files.outputs.all_changed_files) }}

  deploy_services:
    runs-on: ubuntu-latest
    needs: get_services
    strategy:
      matrix:
        service: ${{ fromJson(needs.get_services.outputs.modifiedServices) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Deploy Service
        run: |
          echo "Deploying modified service: ${{ matrix.service }}"
          echo "build"
