name: Dynamic Matrix SURE

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  get_services:
    runs-on: ubuntu-20.04
    outputs:
      services: ${{ steps.get_services.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 2

      - name: Get list of services
        id: get_services
        run: |
          # Finding directories starting with "service-" in src/packages
          service_list=$(find ./packages -type d -name 'service-*' -exec basename {} \;)
          echo "Found services:"
          echo "$service_list"
          echo "after-----------------"
          # Join the list into a comma-separated string
          service_list=$(echo "$service_list" | tr '\n' ',')
          service_list="${service_list%,}"  # Remove trailing comma

          echo "-----------------------------"
          echo "$service_list"
          echo "services=$service_list" >> $GITHUB_OUTPUT
          echo "${{toJson(env)}}"
          echo $GITHUB_OUTPUT
        shell: bash

  get_changes:
    runs-on: ubuntu-20.04
    needs: get_services
    outputs:
      modifiedServices: ${{ steps.check_changes.outputs.modifiedServices }}
      editedModifiedServices: ${{ steps.arrayformat.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Check for changes
        id: check_changes
        run: |
          # Retrieve the service list from Get_services job
          service_list="${{ needs.get_services.outputs.services }}"
          IFS=',' read -ra services <<< "$service_list"
          echo "Found changed files:"
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"

          modified_services=()
          for service in "${services[@]}"; do
            for file in $changed_files; do
              if [[ "$file" == "packages/$service"* ]]; then
                echo "$file changed in $service"
                modified_services+=("$service")
                break
              fi
            done
          done

          # Join the modified services into a comma-separated list
          modified_services=$(IFS=,; echo "${modified_services[*]}")
          echo "modifiedServices=$modified_services" >> $GITHUB_OUTPUT
        shell: bash

      - name: Array formatting
        id: arrayformat
        uses: mad9000/actions-find-and-replace-string@5
        with:
          source: ${{ toJson(steps.check_changes.outputs.modifiedServices) }}
          find: ','
          replace: '","'
          replaceAll: true

  deploy_services:
    runs-on: ubuntu-latest
    permissions:
          issues: write
    needs: get_changes
    strategy:
      matrix:
        service: ${{ fromJson(format('[{0}]', needs.get_changes.outputs.editedModifiedServices)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 2

      - name: Deploy Service
        run: |
          echo "Deploying modified service: ${{ matrix.service }}"
          echo "build"
