name: On Comment Workflow

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  comment-triggered:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      trigger: ${{ steps.branch-deploy.outputs.continue }}
      head_sha: ${{ steps.get_pr.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup GitHub CLI
      #   run: |
      #     echo "GH_TOKEN=${{ github.token }}" >> $GITHUB_ENV
      #     gh auth status

      - uses: github/branch-deploy@v10.4.1
        id: branch-deploy
        with:
          trigger: '.deploy'

      - name: display SHA
        run: echo "head of PR ${{ github.event.issue.number }} is ${{ steps.branch-deploy.outputs.sha }}"

      - name: is this a deploy comment?
        id: is_deploy_comment
        run: |
          if [[ "${{ github.event.comment.body }}" == *".deploy"* ]]; then
            echo "This is a deploy comment"
          else
            echo "This is not a deploy comment"
          fi

      - name: Check if the comment is on a PR
        id: is_pr_comment
        run: |
          if [[ "${{ github.event.issue.pull_request.url }}" != null ]]; then
            echo "This is a PR comment"
          else
            echo "This is not a PR comment"
          fi

      - name: log ref and base ref
        run: |
          echo "ref: ${{ steps.branch-deploy.outputs.ref }}"
          echo "base ref: ${{ steps.branch-deploy.outputs.base_ref }}"
