name: On Comment Workflow

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  comment-triggered:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get comment information
        id: comment
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "comment_body=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "comment_body=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Process comment
        run: |
          echo "Comment body: ${{ steps.comment.outputs.comment_body }}"
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "Processing comment on issue #${{ steps.comment.outputs.issue_number }}"
          else
            echo "Processing comment on PR #${{ steps.comment.outputs.pr_number }}"
          fi
