name: On Comment Workflow

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  comment-triggered:
    runs-on: ubuntu-latest
    outputs:
      trigger: ${{ steps.branch-deploy.outputs.continue }}
      head_sha: ${{ steps.get_pr.outputs.sha }}
    steps:
      - uses: github/branch-deploy@v1.0.0
        id: branch-deploy
        with:
          trigger: '.deploy'

      - name: Get the HEAD SHA of the PR
        id: get_pr
        run: |
          echo "gh api /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} --jq"
          echo "sha=$(gh api /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} --jq .head.sha)" >> $GITHUB_OUTPUT

      - name: display SHA
        run: echo "head of PR ${{ github.event.issue.number }} is ${{ steps.get_pr.outputs.sha }}"

      - name: is this a deploy comment?
        id: is_deploy_comment
        run: |
          echo "is_deploy_comment ${{ steps.get_pr.outputs.sha }}"
