name: Trigger Build Fake A

on:
  workflow_dispatch:
    inputs:
      printval:
        description: 'valeur à afficher'
        required: true
        type: string

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to trigger Build Fake A
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger_build_fake_a", "client_payload":{"printval":"${{ inputs.printval }}"}}'
